### ISSUE TITLE
Using navigator.clipboard API to Copy Multiple Elements (Including Images and Text)

### ISSUE THREAD

**Issue by ulises-jeremias** [nanlabs/frontend-reference#33]
### Describe the feature
I would like to request guidance on utilizing the [navigator.clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) API to copy multiple elements, including images and text, to the clipboard in a single action. This feature enhancement would improve the user experience by enabling users to copy a combination of content for sharing purposes.

### Use Case
I am seeking to enhance our web applications' functionalities by allowing users to copy both images and text in a seamless manner. This would simplify content sharing via email and other platforms, streamlining the process for our users.

### Proposed Solution
One potential approach is to leverage the **navigator.clipboard** API along with HTML content. By crafting HTML that combines images and text, we can create clipboard content that can be copied in a unified manner. Other approach is to write multiple ClipboardItems.

A step-by-step guide or code example demonstrating this process would be invaluable in implementing this feature.

### Other Information
Obviously there are external libraries, but I believe harnessing the native navigator.clipboard API aligns well with our goal of simplicity and reliability.

### Acknowledgements
* [ ] I may be able to implement this feature request
* [ ] This feature might incur a breaking change

### Version used
latest main branch

### Environment details (OS name and version, etc.)
any

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/85ztrkpav) by [Unito](https://www.unito.io)

**Comment by ulises-jeremias** [comment]
@Toti-Biasotti the idea is to add a new README.md file at `examples/navigator-clipboard-guide/README.md`

**Comment by ulises-jeremias** [comment]
@Toti-Biasotti I unassigned this issue since I added the label for the Hacktoberfest

**Comment by ansh-saini** [comment]
Hi. I would like to work on this. Can this be assigned to me?

**Comment by ulises-jeremias** [comment]
@ansh-saini sure! let me know if you need any help on this!

**Comment by ansh-saini** [comment]
I do need some clarity on what exactly it is that we're trying to achieve here.

Copy pasting text and images together from a website into an email is a feature that browsers provide already. I don't think we need to write any code for that.

https://github.com/nanlabs/frontend-reference/assets/32511936/859cc357-0919-49eb-aded-b45d1e580940

Maybe I'm missing something. It would be really helpful if you can explain the problem to me with an example. 
Thank you

**Comment by ulises-jeremias** [comment]
> I do need some clarity on what exactly it is that we're trying to achieve here.
> 
> Copy pasting text and images together from a website into an email is a feature that browsers provide already. I don't think we need to write any code for that.
> 
> https://github.com/nanlabs/frontend-reference/assets/32511936/859cc357-0919-49eb-aded-b45d1e580940
> 
> Maybe I'm missing something. It would be really helpful if you can explain the problem to me with an example. 
> Thank you
> 

Great question! In this case we want to have a guide or Example showing how to do exactly that but programatically with JS using the navigator API 😊

**Comment by ansh-saini** [comment]
Okay, so to make sure I understand correctly:
I should setup an example where a user can press a button to copy some stuff (text+image) to the clipboard, and give them an area where they can paste it (either using a button, or using the keyboard shortcut).

Is that it?

**Comment by ulises-jeremias** [comment]
> Okay, so to make sure I understand correctly:
> I should setup an example where a user can press a button to copy some stuff (text+image) to the clipboard, and give them an area where they can paste it (either using a button, or using the keyboard shortcut).
> 
> Is that it?

Exactly! You can choosing whether to do a small example implementation that can be executed or a Guide in a markdown file explaining hoy to do it

**Comment by ulises-jeremias** [comment]
@ansh-saini do you have any updates on this?

**Comment by ansh-saini** [comment]
Hey, sorry I was unable to work on this.
I have asked my friend @ayushraj17. He will take this up and work on it.

**Comment by ayushraj17** [comment]
I will work on this

**Comment by ulises-jeremias** [comment]
@ayushraj17 I assigned this issue to you!

**Comment by ulises-jeremias** [comment]
@ayushraj17 hey! any update on this? anything I can do to help? 👀

**Comment by ulises-jeremias** [comment]
I just assigned this issue to @Toti-Biasotti 
He will work on this next week

**Comment by Toti-Biasotti** [comment]
Perfect! I will working on this, right away
